#!/bin/sh

cat <<EOF > /tmp/env.js
window._env_ = {
  VITE_KEYCLOAK_BASE_URL: "${VITE_KEYCLOAK_BASE_URL}",
  VITE_KEYCLOAK_REALM: "${VITE_KEYCLOAK_REALM}",
  VITE_KEYCLOAK_CLIENT_ID: "${VITE_KEYCLOAK_CLIENT_ID}",
  VITE_AUTH_SERVICE_URL: "${VITE_AUTH_SERVICE_URL}",
  VITE_PROFILE_SERVICE_URL: "${VITE_PROFILE_SERVICE_URL}",
  VITE_LEARNING_SERVICE_URL: "${VITE_LEARNING_SERVICE_URL}",
  VITE_SCHEDULING_SERVICE_URL: "${VITE_SCHEDULING_SERVICE_URL}",
  VITE_CHAT_SERVICE_URL: "${VITE_CHAT_SERVICE_URL}",
  VITE_PAYMENT_SERVICE_URL: "${VITE_PAYMENT_SERVICE_URL}"
};
EOF

exec "$@"
